language: go

go:
 - 1.13.4

script:
  # Install go-docker
  - dir=$(mktemp -d) 
  - git clone https://github.com/go-swagger/go-swagger "$dir" 
  - cd "$dir"
  - go install ./cmd/swagger
  # Print swagger version
  - swagger version
  # Validate swagger.yml
  - swagger validate swagger.yml
