language: go

go:
 - 1.13.4

script:
  # Save src dir
  - src_dir=$(pwd)
  # Install go-docker
  - temp_dir=$(mktemp -d)
  - git clone https://github.com/go-swagger/go-swagger "$temp_dir"
  - cd "$temp_dir"
  - go install ./cmd/swagger
  # Print swagger version
  - swagger version
  # Switch to src dir
  - cd "$src_dir"
  # Print current dir
  - pwd
  # Validate swagger.yml
  - swagger validate swagger.yml
  # generate swagger server
  - swagger generate server -A TodoList -f ./swagger.yml
  # install missing packages
  - go get -u -f ./...
  # install swagger server
  - go install ./cmd/todo-list-server/
  # run installed swagger server
  - $GOPATH/bin/todo-list-server --port=8080 &
  # wait a bit for server to come up and then verify that the server responds
  - sleep 2s
  - curl -i http://localhost:8080
